#!/usr/bin/env bash

SCRIPTS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
ROOT_DIR=$SCRIPTS_DIR/../../..

if ! [ -d $ROOT_DIR/tmp ]; then
  mkdir $ROOT_DIR/tmp
fi

$SCRIPTS_DIR/stop_server
$SCRIPTS_DIR/start_server
crystal spec $(find ./spec/acceptance -name '*_spec.cr')
$SCRIPTS_DIR/stop_server
